FROM golang:1.22-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev wget curl

COPY go.mod ./
RUN go mod download && \
    go mod tidy

COPY . .

RUN go mod tidy

ENV GIN_MODE=debug
ENV PORT=8080

RUN go build -o main ./cmd/server

EXPOSE 8080

CMD ["./main"] 